# Generated by Django 4.0.4 on 2022-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cgpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sem1', models.FloatField(max_length=255)),
                ('sem2', models.FloatField(max_length=255)),
                ('sem3', models.FloatField(max_length=255)),
                ('sem4', models.FloatField(max_length=255)),
                ('sem5', models.FloatField(max_length=255)),
                ('sem6', models.FloatField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sgpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sub1', models.CharField(max_length=255)),
                ('credit1', models.FloatField()),
                ('grade1', models.FloatField()),
                ('sub2', models.CharField(max_length=255)),
                ('credit2', models.FloatField()),
                ('grade2', models.FloatField()),
                ('sub3', models.CharField(max_length=255)),
                ('credit3', models.FloatField()),
                ('grade3', models.FloatField()),
                ('sub4', models.CharField(max_length=255)),
                ('credit4', models.FloatField()),
                ('grade4', models.FloatField()),
                ('sub5', models.CharField(max_length=255)),
                ('credit5', models.FloatField()),
                ('grade5', models.FloatField()),
                ('sub6', models.CharField(max_length=255)),
                ('credit6', models.FloatField()),
                ('grade6', models.FloatField()),
                ('sub7', models.CharField(max_length=255)),
                ('credit7', models.FloatField()),
                ('grade7', models.FloatField()),
            ],
        ),
    ]
