# Generated by Django 4.0.4 on 2022-08-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cgpa_sgpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sgpa',
            old_name='credit1',
            new_name='cc1',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='credit2',
            new_name='cc2',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='credit3',
            new_name='cc3',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='credit4',
            new_name='cc4',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='credit5',
            new_name='cc5',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='credit6',
            new_name='cc6',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='credit7',
            new_name='cc7',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='grade1',
            new_name='cg1',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='grade2',
            new_name='cg2',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='grade3',
            new_name='cg3',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='grade4',
            new_name='cg4',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='grade5',
            new_name='cg5',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='grade6',
            new_name='cg6',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='grade7',
            new_name='cg7',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='sub1',
            new_name='cn1',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='sub2',
            new_name='cn2',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='sub3',
            new_name='cn3',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='sub4',
            new_name='cn4',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='sub5',
            new_name='cn5',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='sub6',
            new_name='cn6',
        ),
        migrations.RenameField(
            model_name='sgpa',
            old_name='sub7',
            new_name='cn7',
        ),
    ]
