# Generated by Django 4.1.7 on 2023-03-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificate_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.CharField(choices=[('web', 'Web'), ('app', 'App'), ('aiml', 'AI/ML')], max_length=200),
        ),
    ]
