# Generated by Django 4.1.7 on 2023-03-11 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='tag',
            field=models.CharField(choices=[('cs', 'Coursera'), ('udm', 'UDEMY'), ('kct', 'KCT'), ('fl', 'FutureLearn'), ('gl', 'Great Learning'), ('aws', 'AWS'), ('ms', 'Microsoft')], max_length=200),
        ),
    ]
