# Generated by Django 4.1.7 on 2023-03-11 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_project_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='img_src',
            new_name='img_src1',
        ),
        migrations.AddField(
            model_name='project',
            name='img_src2',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='img_src3',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
